name: NPM Actions

on:
  pull_request:
  push:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          only_changed: True
          prettier_version: 2.8.8
